services:

  devcontainer:
    build: ./.devcontainer
    container_name: NetLogAnalyser-DevContainer
    volumes:
      - ./:/workspaces
    networks:
      - NetLogAnalyser-Network
    command: sleep infinity  # keeps it alive without doing anything

  frontend:
    build: ./frontend
    container_name: NetLogAnalyser-Frontend
    ports:
      - "3000:3000"
    environment:
     - BUILD_MODE=${BUILD_MODE}
    depends_on:
      - backend
    networks:
      - NetLogAnalyser-Network
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: sh /entrypoint.sh
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: NetLogAnalyser-Backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BUILD_MODE=${BUILD_MODE}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    networks:
      - NetLogAnalyser-Network
    restart: unless-stopped

  db:
    image: postgres:18-alpine
    container_name: NetLogAnalyser-DB
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - NetLogAnalyser-Network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  frontend_node_modules:

networks:
  NetLogAnalyser-Network:
    driver: bridge