"""add more fields to refresh token

Revision ID: 0ed28621d716
Revises: 2ae9ced56fb7
Create Date: 2026-06-17 16:34:32.282636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ed28621d716'
down_revision: Union[str, Sequence[str], None] = '2ae9ced56fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('family_id', sa.UUID(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('replaced_by_id', sa.UUID(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('ip_address', postgresql.INET(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('user_agent', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_foreign_key(None, 'refresh_tokens', 'refresh_tokens', ['replaced_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'user_agent')
    op.drop_column('refresh_tokens', 'ip_address')
    op.drop_column('refresh_tokens', 'replaced_by_id')
    op.drop_column('refresh_tokens', 'family_id')
    # ### end Alembic commands ###
