"""add anomaly reasons to log entry

Revision ID: 76d5d7263919
Revises: 0d4f57283732
Create Date: 2026-07-30 20:01:07.551631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76d5d7263919'
down_revision: Union[str, Sequence[str], None] = '0d4f57283732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_entries', sa.Column('anomaly_reasons', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_entries', 'anomaly_reasons')
    # ### end Alembic commands ###
