"""remove is_active column from log entries, add composite indexes

Revision ID: a25bdecd4c5b
Revises: 85a85762d071
Create Date: 2026-07-24 10:48:40.158823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a25bdecd4c5b'
down_revision: Union[str, Sequence[str], None] = '85a85762d071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_api_keys_revoked_at'), 'api_keys', ['revoked_at'], unique=False)
    op.create_index('ix_api_keys_user_id_created_at', 'api_keys', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_api_keys_user_id_revoked_at', 'api_keys', ['user_id', 'revoked_at'], unique=False)
    op.drop_column('api_keys', 'is_active')
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_index('ix_email_verification_tokens_user_id_used_at', 'email_verification_tokens', ['user_id', 'used_at'], unique=False)
    op.create_index('ix_log_entries_user_id_captured_at', 'log_entries', ['user_id', 'captured_at'], unique=False)
    op.create_index('ix_refresh_tokens_user_id_revoked_at', 'refresh_tokens', ['user_id', 'revoked_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refresh_tokens_user_id_revoked_at', table_name='refresh_tokens')
    op.drop_index('ix_log_entries_user_id_captured_at', table_name='log_entries')
    op.drop_index('ix_email_verification_tokens_user_id_used_at', table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.add_column('api_keys', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_index('ix_api_keys_user_id_revoked_at', table_name='api_keys')
    op.drop_index('ix_api_keys_user_id_created_at', table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_revoked_at'), table_name='api_keys')
    # ### end Alembic commands ###
