"""add data_exports table

Revision ID: dbe02b51a10b
Revises: 121e917ecf5c
Create Date: 2026-08-17 22:42:12.372935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbe02b51a10b'
down_revision: Union[str, Sequence[str], None] = '121e917ecf5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_exports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('storage_backend', postgresql.ENUM('local', 's3', name='data_exports_storage_backend_enum'), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'ready', 'failed', name='data_exports_status_enum'), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('triggered_by', postgresql.ENUM('manual', 'retention_job', name='data_exports_triggered_by_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_exports_created_at'), 'data_exports', ['created_at'], unique=False)
    op.create_index(op.f('ix_data_exports_user_id'), 'data_exports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_exports_user_id'), table_name='data_exports')
    op.drop_index(op.f('ix_data_exports_created_at'), table_name='data_exports')
    op.drop_table('data_exports')
    # ### end Alembic commands ###
