on:
  pull_request:
    branches:
      - main
      - staging
    paths-ignore:
      - "**/*.md"
  push:
    branches:
      - main
      - staging
    paths-ignore:
      - "**/*.md"

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "25"
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Intall Node.js Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm run lint --max-warnings=0
  check-branch:
   runs-on: ubuntu-latest
   needs: checks

   steps:
     - name: Only Allow Merge to Main from Staging
       if: github.base_ref == 'main'
       run: |
         if [[ "${{ github.head_ref }}" != "staging" ]]; then
           echo "Only merges from the staging branch are permitted."
           exit 1
         else
           echo "Merge from staging to main successful."
          fi
  deploy:
   runs-on: ubuntu-latest
   needs: check-branch

   steps:
     - name: Checkout Code
       uses: actions/checkout@v6

     - name: Deploy Backend to Render Staging
       if: github.ref == 'refs/heads/staging'
       env:
         staging_backend_deploy_url: ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK_STAGING }}
       run: curl -X POST "$staging_backend_deploy_url"

     - name: Deploy Frontend to Render Staging
       if: github.ref == 'refs/heads/staging'
       env:
         staging_frontend_deploy_url: ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK_STAGING }}
       run: curl -X POST "$staging_frontend_deploy_url"

       
     - name: Deploy Backend to Render Main
       if: github.ref == 'refs/heads/main'
       env:
         prod_backend_deploy_url: ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK_PROD }}
       run: curl -X POST "$prod_backend_deploy_url"

     - name: Deploy Frontend to Render Main
       if: github.ref == 'refs/heads/main'
       env:
         prod_frontend_deploy_url: ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK_PROD }}
       run: curl -X POST "$prod_frontend_deploy_url"
